# Name of the workflow
name: Create Release and Upload Binaries

# **CHANGE 1: This workflow now runs ONLY on pushing a new tag (e.g., v1.0, v1.2.1)**
on:
  push:
    tags:
      - "v*" # Trigger on tags that start with 'v'
  workflow_dispatch: # Allows manual runs from the Actions tab for testing

jobs:
  # JOB 1: Build the executables for Windows, macOS, and Linux
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller --name "TaskManager" --onefile --windowed task_manager.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: TaskManager-${{ matrix.os }}
          path: dist/TaskManager*

  # **CHANGE 2: A new job to create the release AFTER all builds are successful**
  release:
    # This job depends on the 'build' job finishing successfully
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          # The destination directory for the downloaded files
          path: release_assets/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # This will upload all files from the 'release_assets' directory
          files: release_assets/**/*
